# Generated by Django 4.0.1 on 2022-01-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_resultat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='note',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='note',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='specialite',
            name='classe',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
