# Generated by Django 4.0.1 on 2022-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_classe_id_alter_etudiant_id_alter_matiere_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_nai_etudiant',
            field=models.DateTimeField(verbose_name='Date Naissance'),
        ),
    ]
