# Generated by Django 4.0.1 on 2022-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_etudiant_date_nai_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_nai_etudiant',
            field=models.DateField(verbose_name='Date Naissance'),
        ),
    ]
